# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Alpa' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

#Pods for Alpa

#Firebase Pods
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Crash'

#Facebook Pods
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

#SwiftyJSON
pod 'SwiftyJSON', '~> 3.1'

#Realm Database
pod 'RealmSwift', '~> 2.5.1'

#Alamofire Pods
pod 'Alamofire', '~> 4.4'
pod 'AlamofireImage', '~> 3.1'
end

#Swift 3 Support
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
